Added Aws Elasticache Validade Backup
Sensedia/open-tools pull request #7
Opened 2021-04-22 13:56 UTC by andredeo

**O que foi feito?**
Adcionado o Script, Docker File e Documentação referente ao Aws Elasticache Validade Backup

**Por que foi feito?**

Para compartilhar com a comunidade a solução desenvolvida por nós

2021-04-22 14:20 UTC, aeciopires requested changes

2021-04-22 14:20 UTC, aeciopires commented on aws_elasticache/validate_backup/README.md
> +Copyright Sensedia 2020
@andredeo Como já está público, então sugiro a licença GPLv3 Sensedia 2021 ;-)

2021-04-22 14:20 UTC, aeciopires commented on aws_elasticache/validate_backup/README.md
> +docker run -it --rm -e "PROFILE=\<profile>" -e "REGION=\<region>" -e "_DEBUG_COMMAND=<on|off>" -e "BACKUP_TIME=\<time>" -e "MY_S3_BUCKET=\<bucket_name>" -e "CACHE_SIZE=\<cache_size>" -e "REDIS_VERSIO
@andredeo, o nome da imagem docker que está **opentools/validate_backup_elasticache** vai mudar para outra coisa tal como: **sensedia/validate_backup_elasticache**... 

@alanwds está vendo como acessar a conta da Sensedia no Docker Hub para criar um repositório lá...

2021-04-22 14:20 UTC, aeciopires commented on aws_elasticache/validate_backup/Dockerfile
> +    IAM_AUTHENTICATOR_VERSION="1.16.8"
@andredeo as variáveis que você pede para o usuário criar durante a execução do Docker Run não estão sendo criada aqui... Acho que elas precisam ser criadas aqui e definidos valores default caso estejam vazias, certo?

Ou o script vai funcionar se as variáveis foram passadas apenas durante a execução do comando Docker Run?

2021-04-22 14:20 UTC, aeciopires commented on aws_elasticache/validate_backup/validate_backup_elasticache.sh
> +
@andredeo acho que antes do script começar o trabalho, vale adicionar uma função que verifica se todos os comandos requisitos e arquivos existem durante a execução. Te passarei alguns exemplos no privado...

2021-04-22 14:22 UTC, andredeo commented on aws_elasticache/validate_backup/README.md
> +Copyright Sensedia 2020
Done

2021-04-22 14:25 UTC, andredeo commented on aws_elasticache/validate_backup/Dockerfile
> +    IAM_AUTHENTICATOR_VERSION="1.16.8"
Essas variáveis são usadas na criação da imagem apenas, não na execução do script. Se mais para a frente quebrarem a gente refatora e publica com a nova versão.

2021-04-23 14:19 UTC, aeciopires approved these changes
Parabéns pela qualidade do código @andredeo

2021-04-23 14:32 UTC, merged